In [27]:
import pandas as pd
import numpy as np
print("Hello, there")
d = np.linspace(1,100,10)
print(d)

Hello, there
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]

In [14]:
s = pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [16]:
marks = pd.Series([50,61,16,84,91,99], index=["John", "Mark", "Musef", "Ayan", "Arthur", "Alhaj" ])
marks

John      50
Mark      61
Musef     16
Ayan      84
Arthur    91
Alhaj     99
dtype: int64

In [17]:
data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Delhi", "Mumbai", "Bangalore"]
}

df = pd.DataFrame(data)
df

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [29]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [31]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [34]:
df.dtypes

name    object
age      int64
city    object
dtype: object

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [36]:
df.describe()

        age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [37]:
df.isnull().sum()

name    0
age     0
city    0
dtype: int64